### ISSUE TITLE
Mac executable_path 相关错误

### ISSUE THREAD

**Issue by AndySze** [xiaoshun007/12306Python#21]
错误信息如下，不知道怎么解决：
```bash
===========hack12306 begin===========
映射出发地、目的地...
加载配置文件...
Traceback (most recent call last):
  File "hack12306.py", line 310, in <module>
    hackTickets.start()
  File "hack12306.py", line 294, in start
    self.driver=Browser(driver_name=self.driver_name,executable_path=self.executable_path)
  File "/usr/local/lib/python2.7/site-packages/splinter/browser.py", line 43, in Browser
    return driver(*args, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'executable_path'
```

**Comment by xiaoshun007** [comment]
@AndySze 1、确保config.ini文件中最后一行executable_path，这个配置没有被注释（看是否被加了#）
2、确保config.ini的文件与程序在一个目录中
3、如果不想放在一个目录，也可以使用命令：python hack12306.py --c /usr/config.ini
（/usr/config.ini是config.ini文件的实际位置）
