### ISSUE TITLE
没执行成功，好像驱动的问题？

### ISSUE THREAD

**Issue by SSzhang232010** [xiaoshun007/12306Python#38]
非Python开发人员，报错搞不懂，勉强装好环境。。求大神帮忙！

Mac系统，执行信息如下：

===========hack12306 begin===========
映射出发地、目的地...
加载配置文件...
hack12306.py:41: DeprecationWarning: This method will be removed in future versions.  Use 'parser.read_file()' instead.
  cp.readfp(codecs.open(config_file, "r", "utf-8-sig"))
Traceback (most recent call last):
  File "hack12306.py", line 319, in <module>
    hackTickets.start()
  File "hack12306.py", line 303, in start
    self.driver=Browser(driver_name=self.driver_name,executable_path=self.executable_path)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/splinter/browser.py", line 63, in Browser
    return driver(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/splinter/driver/webdriver/chrome.py", line 35, in __init__
    self.driver = Chrome(chrome_options=options, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/selenium/webdriver/chrome/webdriver.py", line 75, in __init__
    desired_capabilities=desired_capabilities)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 154, in __init__
    self.start_session(desired_capabilities, browser_profile)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 243, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 312, in execute
    self.error_handler.check_response(response)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 237, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: cannot find Chrome binary
  (Driver info: chromedriver=2.35.528157 (4429ca2590d6988c0745c24c8858745aaaec01ef),platform=Mac OS X 10.12.6 x86_64)

**Comment by Skyge** [comment]
@SSzhang232010 首先在你的执行信息中，前三行是在说明一个Warning，开发人员在开发过程中更看重Error，所以此处Warning可以忽略，从Traceback开始便是Error信息，看最后的提示信息：WebDriverException:Message: unknown error: cannot find Chrome binary，所以建议确认Chrome浏览器的驱动chromedrive的安放路径是否书写正确。具体配置信息可参见README.md-->Config说明-->## 路径信息[pathInfo]。

**Comment by SSzhang232010** [comment]
<img width="498" alt="wx20180206-102100 2x" src="https://user-images.githubusercontent.com/20944562/35838700-8ad711ac-0b27-11e8-9d99-4c9a99e2267a.png">
<img width="576" alt="wx20180206-101839 2x" src="https://user-images.githubusercontent.com/20944562/35838706-8f311630-0b27-11e8-92de-8fd315d11540.png">
以上是我chromedrive驱动的路径和配置。应该没错的。
